name: base
channels:
  - defaults
dependencies:
  #- conda
  - python=3.9
  #- _ipyw_jlab_nb_ext_conf
  #- anaconda==2022.10=py39_0
  #- anaconda-navigator
  #- navigator-updater
  - numpy as np
  - pip
  - pandas
  - jupyterquiz
  - md2json
  - hide_code
  - nbconvert
  - import-ipynb
  - ipython-extensions
  - jupytercards
  - ipywidgets import TwoByTwoLayout
  - jupyterquiz import display_quiz 
  - jupytercards import display_flashcards
  - import ipywidgets as widgets
  - md2json
  - json
  - IPython.display import HTML
  - random
  - matplotlib.pyplot as plt
  - import_ipynb
  - md2json


