name: base
channels:
  - defaults
dependencies:
  #- conda
  - python=3.9
  #- _ipyw_jlab_nb_ext_conf
  #- anaconda==2022.10=py39_0
  #- anaconda-navigator
  #- navigator-updater
  - numpy
  - pip
  - pip:
    - pandas
    - jupyterquiz
    - md2json
    - hide_code
    - nbconvert
    - import-ipynb
    - ipython-extensions
    - jupytercards
    - ipywidgets
    - jupytercards
    - md2json
    - json
    - IPython
    - random
    - matplotlib
    - import_ipynb
    - md2json
  
  
