name: base
channels:
  - defaults
dependencies:
  #- conda
  - python=3.9
  #- _ipyw_jlab_nb_ext_conf
  #- anaconda==2022.10=py39_0
  #- anaconda-navigator
  #- navigator-updater
  - numpy
  - pip
  - pandas
  - jupyterquiz
  - md2json
  - hide_code
  - nbconvert
  - import-ipynb
  - ipython-extensions
  - jupytercards
  - ipywidgets.TwoByTwoLayout
  - jupyterquiz.display_quiz 
  - jupytercards.display_flashcards
  - md2json
  - json
  - IPython.display.HTML
  - random
  - matplotlib.pyplot
  - import_ipynb
  - md2json


